### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by DrWhax** [jackel119/CryptoBoi#1]
Hey, your API keys are still in the source code which leads to:

>>> my_bittrex.get_balance('OMG')                                                                                                                  
{u'message': u'', u'result': {u'Available': 144.84327803, u'Requested': False, u'Updated': u'2017-11-25T12:47:17.033', u'Uuid': u'926e5a98-1b9c-46be-963d-4d3171ebb12a', u'AutoSell': None, u'Currency': u'OMG', u'CryptoAddress': None, u'Balance': 144.84327803, u'Pending': 0.0, u'AccountId': 1221663}, u'success': True}>>> 

You probably want to revoke these keys ASAP. pro-tip: make use of a seperate secrets.json file and add that to .gitignore :)

**Comment by jackpordi** [comment]
Cheers man,
Luckily past me was smart enough to use a view-only key just in case...
